FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

# Copy everything
COPY . ./

WORKDIR /App/Veraeasy
RUN cd /App/Veraeasy
# Restore as distinct layers
RUN dotnet restore

RUN dotnet clean

RUN dotnet build

# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/Veraeasy/out .
ENTRYPOINT ["dotnet", "Veraeasy.dll"]